In [3]:
import pandas as pd

### Connect to WRDS

In [1]:
#import wrds
#db = wrds.Connection()

### Daily Security Information (Daily)

In [5]:
'''
sql_query = """
-- Name History Table
SELECT
    crsp.saz_dp_dly.KYPERMNO,
    crsp.saz_dp_dly.CALDT,
    crsp.saz_dp_dly.PRC,
    crsp.saz_dp_dly.RET,
    crsp.saz_dp_dly.RETX,
    crsp.saz_dp_dly.TCAP,
    crsp.saz_dp_dly.VOL
FROM 
    crsp.saz_dp_dly
WHERE
    crsp.saz_dp_dly.CALDT >= '2010-01-01'
"""
dailySecurityInfo = db.raw_sql(sql_query)
dailySecurityInfo.head()
'''

'\nsql_query = """\n-- Name History Table\nSELECT\n    crsp.saz_dp_dly.KYPERMNO,\n    crsp.saz_dp_dly.CALDT,\n    crsp.saz_dp_dly.PRC,\n    crsp.saz_dp_dly.RET,\n    crsp.saz_dp_dly.RETX,\n    crsp.saz_dp_dly.TCAP,\n    crsp.saz_dp_dly.VOL\nFROM \n    crsp.saz_dp_dly\nWHERE\n    crsp.saz_dp_dly.CALDT >= \'2010-01-01\'\n"""\ndailySecurityInfo = db.raw_sql(sql_query)\ndailySecurityInfo.head()\n'

### Daily Security Information (Monthly)

In [6]:
sql_query = """
-- Name History Table
SELECT
    crsp.saz_mth.KYPERMNO,
    crsp.saz_mth.MCALDT,
    crsp.saz_hdr.HCOMNAM,
    crsp.saz_hdr.HTICK,
    crsp.saz_hdr.HSHRCD,
    crsp.saz_hdr.HSICCD,
    crsp.saz_mth.MPRC,
    crsp.saz_mth.MRET,
    crsp.saz_mth.MRETX,
    crsp.saz_mth.MTCAP,
    crsp.saz_mth.MVOL
FROM 
    crsp.saz_mth
INNER JOIN
    crsp.saz_hdr
ON
    crsp.saz_mth.KYPERMNO = crsp.saz_hdr.KYPERMNO
WHERE
    crsp.saz_mth.MCALDT >= '2014-01-01' AND
    crsp.saz_mth.MCALDT <= '2019-01-01' AND
    (
    crsp.saz_hdr.HSHRCD = 10 OR
    crsp.saz_hdr.HSHRCD = 11 OR
    crsp.saz_hdr.HSHRCD = 18
    )
"""
monthlySecurityInfo = db.raw_sql(sql_query)
monthlySecurityInfo.head()

,kypermno,mcaldt,hcomnam,htick,hshrcd,hsiccd,mprc,mret,mretx,mtcap,mvol
0,10001.0,2014-01-31,GAS NATURAL INC,None,11.0,4925.0,9.17,0.147572,0.141968,95844.840797,1768800.0
1,10051.0,2016-11-30,HANGER INC,HNGR,11.0,8093.0,NaN,NaN,NaN,NaN,NaN
2,10051.0,2016-10-31,HANGER INC,HNGR,11.0,8093.0,NaN,NaN,NaN,NaN,NaN
3,10001.0,2014-02-28,GAS NATURAL INC,None,11.0,4925.0,9.36,0.025627,0.020720,97830.716412,872000.0
4,10001.0,2014-03-31,GAS NATURAL INC,None,11.0,4925.0,10.06,0.079594,0.074786,105147.124386,969600.0

### SIC Code Classification

In [7]:
monthlySecurityInfo['SIC_Classification'] = pd.cut(monthlySecurityInfo['hsiccd'].astype(float),
                                               bins=[100, 999, 
                                                     1499, 1799, 
                                                     1999, 3999, 
                                                     4999, 5199,
                                                     5999, 6799, 
                                                     8999, 9729, 
                                                     9999
                                                    ],
                                               labels=['Agriculture, Forestry and Fishing', 
                                                       'Mining', 
                                                       'Construction', 
                                                       'not used', 
                                                       'Manufacturing', 
                                                       'Transportation, Communications, Electric, Gas and Sanitary service',
                                                       'Wholesale Trade',
                                                       'Retail Trade',
                                                       'Finance, Insurance and Real Estate',
                                                       'Services',
                                                       'Public Administration',
                                                       'Nonclassifiable'
                                                      ],
                                               include_lowest=True
                                              )
monthlySecurityInfo.head()

,kypermno,mcaldt,hcomnam,htick,hshrcd,hsiccd,mprc,mret,mretx,mtcap,mvol,SIC_Classification
0,10001.0,2014-01-31,GAS NATURAL INC,None,11.0,4925.0,9.17,0.147572,0.141968,95844.840797,1768800.0,"Transportation, Communications, Electric, Gas ..."
1,10051.0,2016-11-30,HANGER INC,HNGR,11.0,8093.0,NaN,NaN,NaN,NaN,NaN,Services
2,10051.0,2016-10-31,HANGER INC,HNGR,11.0,8093.0,NaN,NaN,NaN,NaN,NaN,Services
3,10001.0,2014-02-28,GAS NATURAL INC,None,11.0,4925.0,9.36,0.025627,0.020720,97830.716412,872000.0,"Transportation, Communications, Electric, Gas ..."
4,10001.0,2014-03-31,GAS NATURAL INC,None,11.0,4925.0,10.06,0.079594,0.074786,105147.124386,969600.0,"Transportation, Communications, Electric, Gas ..."

### Merge Two Dataframes

In [8]:
monthlySecurityInfo['kypermno'] = monthlySecurityInfo['kypermno'].astype(float)
monthlySecurityInfo.head()

,kypermno,mcaldt,hcomnam,htick,hshrcd,hsiccd,mprc,mret,mretx,mtcap,mvol,SIC_Classification
0,10001.0,2014-01-31,GAS NATURAL INC,None,11.0,4925.0,9.17,0.147572,0.141968,95844.840797,1768800.0,"Transportation, Communications, Electric, Gas ..."
1,10051.0,2016-11-30,HANGER INC,HNGR,11.0,8093.0,NaN,NaN,NaN,NaN,NaN,Services
2,10051.0,2016-10-31,HANGER INC,HNGR,11.0,8093.0,NaN,NaN,NaN,NaN,NaN,Services
3,10001.0,2014-02-28,GAS NATURAL INC,None,11.0,4925.0,9.36,0.025627,0.020720,97830.716412,872000.0,"Transportation, Communications, Electric, Gas ..."
4,10001.0,2014-03-31,GAS NATURAL INC,None,11.0,4925.0,10.06,0.079594,0.074786,105147.124386,969600.0,"Transportation, Communications, Electric, Gas ..."

### Implement Strategy

Industry Weighted (SIC) by industry market cap, equal weighted within industry.

In [ ]:
import numpy as np

strategyReturns = {'Period': [], 'strategyReturns': []}

years = pd.date_range('2014-01-01', '2018-01-01', freq='Y')

for year in years:
    # Get top 500 largest market cap companies for the given year
    marketCap500 = monthlySecurityInfo[(pd.DatetimeIndex(monthlySecurityInfo['mcaldt']).year==year.year) & 
                             (pd.DatetimeIndex(monthlySecurityInfo['mcaldt']).month==year.month)][['mtcap', 'kypermno']]
    
    marketCap500 = marketCap500.groupby(by='kypermno').sum().reset_index()
    marketCap500 = marketCap500.sort_values(by='mtcap', ascending=False)[:500]
    
    # Keep Only Identified Constituents
    constituentData = pd.merge(marketCap500.drop('mtcap',axis=1), monthlySecurityInfo, how='inner', left_on='kypermno', right_on='kypermno')[['kypermno', 'hcomnam', 'mret', 'mcaldt', 'mprc', 'mtcap', 'SIC_Classification']]

    months = pd.date_range(year - pd.DateOffset(months=11), year , freq='M')
    for month in months:
        constituentDataMonth = constituentData[(pd.DatetimeIndex(constituentData['mcaldt']).year==month.year) & 
                                 (pd.DatetimeIndex(constituentData['mcaldt']).month==month.month)]
        # Find Weights of Individual SIC Sectors For Given Month (mtcap weighted)
        SICWeights = constituentDataMonth[['mtcap', 'SIC_Classification']]
        SICWeights = SICWeights.groupby(by='SIC_Classification').sum().reset_index()
        SICWeights['mtcapPerc'] = SICWeights['mtcap']/SICWeights['mtcap'].sum()
        SICWeights = SICWeights.set_index('SIC_Classification')
        SICWeights = SICWeights['mtcapPerc'].to_dict()
        constituentDataMonth['Sector_Weight'] = constituentDataMonth['SIC_Classification'].map(SICWeights)
        
        # Assign Weights of companies within SIC Sectors For Given Month (equal weighted)
        internalWeights = constituentDataMonth[['mtcap', 'SIC_Classification']]
        internalWeights = 1/internalWeights['SIC_Classification'].value_counts()
        internalWeights = internalWeights.to_dict()
        constituentDataMonth['Internal_Weight'] = constituentDataMonth['SIC_Classification'].map(internalWeights)
        
        # Calculate Returns
        returns = constituentDataMonth['Sector_Weight']*constituentDataMonth['Internal_Weight']*constituentDataMonth['mret'].astype(float)

        strategyReturns['strategyReturns'].append((returns.sum()))
        strategyReturns['Period'].append(month)


currentPeriod = []
strategyValues = {'Period': strategyReturns['Period'], 'strategyValues': []}
currentValue = 100
strategyValues['strategyValues'].append(currentValue)
for return_value in strategyReturns['strategyReturns']:
    currentValue = currentValue * (1 + return_value)
    strategyValues['strategyValues'].append(currentValue)

strategyValues = {'Period': strategyReturns['Period'], 'strategyValues': strategyValues['strategyValues'][1:]}

<ipython-input-9-cc03547b6aac>:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  constituentDataMonth['Sector_Weight'] = constituentDataMonth['SIC_Classification'].map(SICWeights)
<ipython-input-9-cc03547b6aac>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  constituentDataMonth['Internal_Weight'] = constituentDataMonth['SIC_Classification'].map(internalWeights)

In [102]:
import math

returnData = pd.DataFrame()
# Calculate Returns for Every Asset
for asset in results.head():
    returnData[str(asset + "_returns")] = (results[asset] - results[asset].shift(1)) / results[asset].shift(1)

# Drop first row of Returns
returnData = returnData.drop(returnData.index[0])

# Assets
assets = returnData.columns

# Calculate Historical Returns
historicalReturns = returnData.mean()

# Convert Returns to Array
historicalReturns = historicalReturns.to_numpy()

# Calculate Risk
risk = returnData.std().to_numpy()

for i, asset in enumerate(assets):
    annualRet = (1+historicalReturns[i])**12 - 1
    annualSD = risk[i] * math.sqrt(12)
    print(f'Annual Return ({asset}): {annualRet}')
    print(f'Annual Risk ({asset}): {annualSD}')
    print(f'Annual S/R ({asset}): {(annualRet-.02)/annualSD}')

Annual Return (strategyValues_returns): 0.1855816565344759
Annual Risk (strategyValues_returns): 0.0997206334376686
Annual S/R (strategyValues_returns): 1.660455322297711